/*
 * TMAX FDL header file. automatically generated by fdlc
 * Field Table File : ../fdl/info.f
 */



#define AMOUNT 	 ((FLDKEY)201326693) /* number: 101 type: int */ 
#define FROM 	 ((FLDKEY)469762150) /* number: 102 type: string */ 
#define TO 	 ((FLDKEY)469762151) /* number: 103 type: string */ 
